OpenAQDemo/Models/CountryMeasurementsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OpenAQDemo.Models
{
    public class CountryMeasurementsModel
    {
        public int count { get; set; }        
        public string name { get; set; }
    }
}

OpenAQDemo/Models/ErrorViewModel.cs
using System;

namespace OpenAQDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OpenAQDemo/Models/OpenAQ_City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OpenAQDemo.Models
{
    public class OpenAQ_City
    {
        public class Meta
        {
            public string name { get; set; }
            public string license { get; set; }
            public string website { get; set; }
            public int page { get; set; }
            public int limit { get; set; }
            public int found { get; set; }
        }

        public class Result
        {
            public string country { get; set; }
            public string name { get; set; }
            public string city { get; set; }
            public int count { get; set; }
            public int locations { get; set; }
        }
        
       public Meta meta { get; set; }
       public List<Result> results { get; set; }       
    }
}

OpenAQDemo/Models/OpenAQ_Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OpenAQDemo.Models
{
    public class OpenAQ_Country
    {
        public class Meta
        {
            public string name { get; set; }
            public string license { get; set; }
            public string website { get; set; }
            public int page { get; set; }
            public int limit { get; set; }
            public int found { get; set; }
        }

        public class Result
        {
            public string code { get; set; }
            public int count { get; set; }
            public int locations { get; set; }
            public int cities { get; set; }
            public string name { get; set; }
        }

        public Meta meta { get; set; }
        public List<Result> results { get; set; }

    }
}

OpenAQDemo/Models/OptionsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OpenAQDemo.ViewModels.Options;
using Newtonsoft.Json;

namespace OpenAQDemo.Models
{
    public class OptionsModel
    {
        // Get options
        public static OptionsViewModel GetOptions()
        {
            OptionsViewModel model = new OptionsViewModel();

            model.Options = OpenAQDemo.Startup.openAQHelper.GetOptions();

            return model;
        }

        // Get all cities
        public static CitiesViewModel GetCities()
        {
            CitiesViewModel model = new CitiesViewModel();

            model.Cities = Startup.openAQHelper.GetCities();

            return model;
        }

        // Get all countries
        public static CountriesViewModel GetCountries()
        {
            CountriesViewModel model = new CountriesViewModel();

            model.Countries = Startup.openAQHelper.GetCountries();

            return model;
        }

        // Get the measurements for a certain
        public static CountryMeasurementsViewModel GetCountryMeasurements(string countryCode)
        {
            CountryMeasurementsViewModel model = new CountryMeasurementsViewModel();

            model.Measurements = Startup.openAQHelper.GetCountryMeasurements(countryCode);

            return model;
        }
    }
}

OpenAQDemo/ViewModels/Options/CitiesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using OpenAQDemo.Models;

namespace OpenAQDemo.ViewModels.Options
{
    public class CitiesViewModel
    {
        public List<OpenAQ_City.Result> Cities { get; set; }
    }
}

OpenAQDemo/ViewModels/Options/CountriesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using OpenAQDemo.Models;

namespace OpenAQDemo.ViewModels.Options
{
    public class CountriesViewModel
    {
        public List<OpenAQ_Country.Result> Countries { get; set; }
    }
}

OpenAQDemo/ViewModels/Options/CountryMeasurementsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OpenAQDemo.Models;

namespace OpenAQDemo.ViewModels.Options
{
    public class CountryMeasurementsViewModel
    {
        public List<CountryMeasurementsModel> Measurements { get; set; }
    }
}

OpenAQDemo/ViewModels/Options/OptionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace OpenAQDemo.ViewModels.Options
{
    public class OptionsViewModel
    {        
        public List<KeyValuePair<int, string>> Options { get; set; }
    }
}

OpenAQDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpenAQDemo.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OpenAQDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {   
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OpenAQDemo/Controllers/OptionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OpenAQDemo.ViewModels.Options;
using OpenAQDemo.Models;
using Newtonsoft.Json;

namespace OpenAQDemo.Controllers
{
    public class OptionsController : Controller
    {
       
        // Populate dropdown with options
        [HttpPost]
        public string GetOptions()
        {
            var options = OptionsModel.GetOptions();
            return JsonConvert.SerializeObject(options);
        }

        // User selected cities
        [HttpPost]
        public string GetCities()
        {
            var citiesResults = OptionsModel.GetCities();
            return JsonConvert.SerializeObject(citiesResults);
        }

        // User selected countries
        [HttpPost]
        public string GetCountries()
        {
            var countriesResults = OptionsModel.GetCountries();
            return JsonConvert.SerializeObject(countriesResults);
        }

        // User clicked on a country measurement
        [HttpPost]
        public string ShowCountryMeasurements(string countryCode)
        {
            var measurementResults = OptionsModel.GetCountryMeasurements(countryCode);
            return JsonConvert.SerializeObject(measurementResults);
        }
    }
}

OpenAQDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Open AQ Platform API Demo</h1>
    <div>
        <strong>An API for open air quality data.</strong>
        <br />
    </div>
</div>

<br/>

@Html.Partial("_ViewOptions")

OpenAQDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OpenAQDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OpenAQDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OpenAQDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

OpenAQDemo/Views/Shared/_ViewOptions.cshtml
@using OpenAQDemo.ViewModels.Options
@model OptionsViewModel

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">

    // Clear the tables with the results
    function ClearResults() {
        $('#tableResults').html('');
        $('#selectionResults').html('');
    }
    // Show where the measurements came for each country
    function showCountryMeasurements(countryCode) {
               
         $.ajax({
            url: '@Url.Action("ShowCountryMeasurements", "Options")',
            datatype: 'JSON',
            type: 'POST',
            data: { countryCode },
            success: function (data) {

                // Get data
                var measurementsList = jQuery.parseJSON(data);

                // if no results then exit
                if (jQuery.isEmptyObject(measurementsList)) {
                    return;
                }

                // Prepare list with table results
                var total = 0;
                var tableStr = "<table border=1>";
                tableStr += "<tr><th>Index</th><th>City</th><th>Count</th></tr>";
                $.each(measurementsList.Measurements, function (ndx) {
                    tableStr +=
                        "<tr><td>" + ndx +
                        "</td><td>" + measurementsList.Measurements[ndx].name +
                        "</td><td>" + measurementsList.Measurements[ndx].count +
                        "</td></tr>";

                    total += measurementsList.Measurements[ndx].count;
                });
                tableStr += "<tr><td>&nbsp;</td><td><strong>Total</strong></td><td><strong>" + total + "</strong></td></tr>";
                tableStr += "</table>";
                $('#selectionResults').html(tableStr);

            },
            error: function (error) {
                // Clear results
                $('#selectionResults').html('');

                alert(error.responseText);
            }
        });

    }

    $(document).ready(function () {

        // Load city data
        function displayCities() {

             $.ajax({
                url: '@Url.Action("GetCities", "Options")',
                datatype: 'JSON',
                type: 'POST',
                data: { },
                success: function (data) {

                    // Get data
                    var cities = jQuery.parseJSON(data);

                    // if no results then exit
                    if (jQuery.isEmptyObject(cities)) {
                        return;
                    }

                    // Prepare list with table results
                    var tableStr = "<table border=1>";
                    tableStr += "<tr><th>Index</th><th>City</th><th>Country Code</th><th>Count</th></tr>";
                    $.each(cities.Cities, function (ndx) {
                        tableStr +=
                            "<tr><td>" + ndx +
                            "</td><td>" + cities.Cities[ndx].city +
                            "</td><td>" + cities.Cities[ndx].country +
                            "</td><td>" + cities.Cities[ndx].count +
                            "</td></tr>";
                    });
                    tableStr += "</table>";
                    $('#tableResults').html(tableStr);

                    // Clear selection results 
                    $('#selectionResults').html('');

                },
                 error: function (error) {
                     // Clear results
                     ClearResults();

                    alert(error.responseText);
                }
             });

        }

        // Load country data
        function displayCountries() {

            $.ajax({
                url: '@Url.Action("GetCountries", "Options")',
                datatype: 'JSON',
                type: 'POST',
                data: { },
                success: function (data) {

                    // Get data
                    var countries = jQuery.parseJSON(data);

                    // if no results then exit
                    if (jQuery.isEmptyObject(countries)) {
                        return;
                    }

                    // Prepare list with table results
                    var tableStr = "<table border=1>";
                    tableStr += "<tr><th>Index</th><th>Country</th><th>Country Code</th><th>Count</th><th>Cities</th></tr>";
                    $.each(countries.Countries, function (ndx) {
                        tableStr +=
                            "<tr><td>" + ndx +
                            "</td><td>" + countries.Countries[ndx].name +
                            "</td><td>" + countries.Countries[ndx].code +
                            "</td><td><a href=\"#\" onclick=\"javascript:showCountryMeasurements('"+ countries.Countries[ndx].code +"');return false;\">" + countries.Countries[ndx].count + "</href>" +
                            "</td><td>" + countries.Countries[ndx].cities +
                            "</td></tr>";
                    });
                    tableStr += "</table>";
                    $('#tableResults').html(tableStr);

                },
                 error: function (error) {
                     // Clear results
                     ClearResults();

                    alert(error.responseText);
                }
            });

        }

        // Do something with user's selection
        function DisplaySelection(selectionIndex) {
            switch (selectionIndex) {
                case 1:
                    displayCities();
                    break;
                case 2:
                    displayCountries();
                    break;
                default:
                    break;
            }
        }

        // Populate the options drop down
        function populateOptions() {
            $.ajax({
                url: '@Url.Action("GetOptions", "Options")',
                datatype: 'JSON',
                type: 'POST',
                data: { },
                success: function (data) {

                    // Get data
                    var options = jQuery.parseJSON(data);

                    // If no results then exit
                    if (jQuery.isEmptyObject(options)) {
                        return;
                    }

                    // Prepare list of options
                    $('#optionsList').append($('<option>', { value: 0, text: 'Please select...' }));
                    $.each(options.Options, function () {
                        $('#optionsList').append($('<option>', { value: this['Key'], text: this['Value']}));
                    })

                },
                error: function (error) {

                    // Clear results
                    ClearResults();

                    alert(error.responseText);
                }
            });
        }

        // Setup listener for options dropdown
        $('#options').on('change', function () {
            // Convert to number
            var selectionIndex = Number($(this).find(":selected").val());            
            // Check for number
            if (!isNaN(selectionIndex) && selectionIndex > 0) {
                // If user selection is valid then call display
                DisplaySelection(selectionIndex);
            } else {
                // Clear results
                ClearResults();
            }
        });

        // Populate options drop down
        populateOptions();

    });

</script>


<div id="options">
Select an option
    <select id="optionsList">
        
    </select>
</div>

<div style="display: table;" id="divResults">
    <div style="float:left;" id="tableResults">

    </div>

    <div style="float:left; margin-left: 20px;" id="selectionResults">
       
    </div>
</div>